[workspace]
authors = ["PaulKMueller <paulkonstantinmueller@gmail.com>"]
channels = ["conda-forge"]
name = "Uncertainty-aware-Blur-Prior"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[feature.lint.tasks]
pci = "pre-commit install"
pc = "pre-commit run --all"
mypy = "mypy ."
[dependencies]
pytorch-gpu = "*"
mne = ">=1.10.2,<2"
torchvision = ">=0.12.0,<0.13"
lightning = ">=2.0.9.post0,<3"
omegaconf = ">=2.3.0,<3"
open-clip-torch = ">=2.32.0,<3"
tensorboard = ">=2.11.2,<3"
tensorboardx = ">=2.6.2.2,<3"
opencv = ">=4.6.0,<5"
snakeviz = ">=2.2.2,<3"
wandb = ">=0.22.3,<0.23"

[feature.lint.dependencies]
pre-commit = ">=4.3.0,<5"
mypy = "*"

[environments]
lint = ["lint"]
default = ["default"]
